name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta automáticamente cada hora
  workflow_dispatch:     # Permite la ejecución manual desde la pestaña "Actions"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update activity section
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Refactor: Update recent activity [skip ci]"
          MAX_LINES: 5
